Fix version
ascoderu/xtarfile pull request #11
Opened 2022-03-18 17:41 UTC by botelhoa

Version file currently being pulled in from `version.txt` which does not exist. I replaced it with the latest version number in pypi

2022-03-18 20:22 UTC, c-w reviewed
Oh how strange. Good catch! Could you re-create the `version.txt` with content `0.1.0`? Just so we don't need to also update `MANIFEST.in` etc. Thanks in advance!

2022-03-18 20:37 UTC, nzola commented
Thanks Austin for the catch and thanks Clemens for responding to Austin!

On Fri, Mar 18, 2022 at 1:22 PM Clemens Wolff ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Oh how strange. Good catch! Could you re-create the version.txt with
> content 0.1.0? Just so we don't need to also update MANIFEST.in etc.
> Thanks in advance!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ascoderu/xtarfile/pull/11#pullrequestreview-914833679>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEH5MM3ERLNT4XC2RAAUYM3VATQXNANCNFSM5RCPQ2IA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-03-18 20:40 UTC, botelhoa commented
Done!

2022-03-19 13:09 UTC, c-w requested changes

2022-03-19 13:09 UTC, c-w commented on version.txt
> +"0.1.0"
```suggestion
0.1.0
```

2022-03-21 14:13 UTC, botelhoa commented on version.txt
> +"0.1.0"
String quotes removed

2022-03-21 16:12 UTC, c-w approved these changes

2022-03-21 16:14 UTC, merged